# Generated by Django 3.1.7 on 2021-04-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleprocess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('products_ids_and_qty', models.JSONField(default=dict)),
                ('price_summarized', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='saleprocess.profile')),
            ],
        ),
    ]
