# Generated by Django 3.1.7 on 2021-04-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleprocess', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_summarized',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
        ),
    ]
